micronaut:
  application:
    name: backendchallenge
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'th3r0c3123'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
flyway:
  datasources:
    default:
      locations: classpath:db/migration
      enabled: true
      baseline-on-migrate: true
jpa.default.properties.hibernate.hbm2ddl.auto: none

