package dev.leonardolemos.test;

public class Constants {
    public static final String STRING_WITH_258_CHAR = "lsyhgmppqxbwtmgckoyvqmmqauimoynwhgjrkehzaaaonxxaijvsvryyunhfpsimuvelrtjlzoxqpijwbihubiiiovdmdhrnnioxauellcqshnahvxmsdxhgewoyewmhoisumscwzylbblhdergdtszzxfudgbgxznkvbasdqhoynzzwgzvruvgpetaomrqdyzmimxhgwqitepqoiopvjiatnvpoteeaggtngxgkznuqwqxxfagoxvbzgsprwsfrjc\n" +
            "krnaxrmqbrhdbbnecbemolcsibqjzztigpoqpnugdhyflnyijibbctifnqljzektzytjycendgizaitwuadugireioutiazqbvmecfzkutdvxjkpedotkcisiyelhdnskeytqoztbvvdqocjabxzxnkfhjeaqnandllxnojvszbtaghdtkqggsbyydrcwdcyglpnrjpttwwmqmwqdqghpgehlqoafmeoqukatcfwqxzojllsylbrnzlqbipwhfvlkz\n" +
            "ztmvsmfhxsmditbkgfizxqiylyawzecisadkfekmzpeeenbcpgejlvcdfjaazhnuhyscvbthucurjkokqvodtanspdcpttxlywrochkmkpnumxmbanusgwmetdkuvukmjvlcjzrdjfawxhghrfkeftszsxwqfcjbjszttpjnxlkrxahphyeolwcrorqfquoohlvevrpmpwdclyheeohsyshitehkcijxraiodwzimbuqnifyzmuydjgsgptpzfktsj\n" +
            "snivhfkegfcxxkexwdpladfwwzaesmvrepdignnfrcglxuvwhtrieqjvbuccmnpffuctmvkajlbsxfnjcvaxzjldgbnavlwajnexdixituhitxerxtsjboksjdxohvvlsokojmabptdbggaradxaejabkurzkynynpdjdesvidfytacmxxufpmabbolwezoqhhlypctdahhebqpbhrxsgxwhneklicpxhalbuopolegddholljemnirologhwfmykh\n" +
            "qflmrgntnywgyehugismynripnjzhvrbyfkvbmojzaqzbzmromdjtvntbnqorxemrdfdojbmzespiebkmhjmuytopmbwwvmnkgvyttirimflbpsanidbutwvbpegxjkiplaahoddcrownreigfvdjfnrjmbhwqiifdwcvsrrdjzyuoiqdmsvrhonilgcagyzfslezxuceqjccmskszqjwjlirrspgtcwqpwqxreptimofzqohjaombtvrfmzregatd";
}
